apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ta-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    version: 3.1.0
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: '3.1'
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
    replicas: 1
    resources: 
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources: 
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi
    storage:
      type: ephemeral